# Generated by Django 3.2.20 on 2023-07-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(default=None),
        ),
    ]
