# Generated by Django 3.2.20 on 2023-07-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(default=None, verbose_name='Phone Number'),
        ),
    ]
