# Generated by Django 3.2.20 on 2023-07-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230731_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='accounts/default.png', upload_to='accounts/'),
        ),
    ]
